name: mangareader
description: "MangaDex Reader"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  js: ^0.7.2
  socks5_proxy: ^2.1.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  extended_image: ^10.0.1
  flutter_cache_manager: ^3.4.1
  dio: ^5.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
